title: Kumarsalugu's blog
author: kumar salugu
email: salugudharanikumar@gmail.como
description: > # this means to ignore newlines until "baseurl:"
  Hey everyone. Welcome to my blog. Here you can checkout my projects and its latest updates

# social links
twitter_username: saluguD # DO NOT include the @ character, or else the build will fail!
github_username:  kumarsalugu # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
